Verifica: Verifica.o Random_Quick_Sort.o
	gcc -g -o Verifica Verifica.o Random_Quick_Sort.o && rm *.o
Verifica.o: Verifica.c Verifica.h
	gcc -g -c Verifica.c
Random_Quick_Sort.o: Random_Quick_Sort.c Verifica.h
	gcc -g -c Random_Quick_Sort.c
