Verifica: Verifica.o Insertion_Sort.o
	gcc -g -o Verifica Verifica.o Insertion_Sort.o && rm *.o
Verifica.o: Verifica.c Verifica.h
	gcc -g -c Verifica.c
Insertion_Sort.o: Insertion_Sort.c Verifica.h
	gcc -g -c Insertion_Sort.c
